<a href="https://colab.research.google.com/github/santoshiranabhat02/AI-bootcamp/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy(numerical Python)**
         python slow for math, numpy fast for math


In [42]:
import numpy as np

python list and numpy array[np.array like function for numpy and list for python]

In [43]:
python_list=[1,2,3,4,5,6,7,8,9]
numpy_array=np.array([1,2,3,4,5,6,7,8])

print(python_list)
print(numpy_array)


[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8]


*2 [python writes the same list twice and numpy muktiplies it by 2

In [44]:
print(python_list*2)
print(numpy_array*2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 2  4  6  8 10 12 14 16]


Numpy array

In [45]:
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [46]:
b=[1,2,3,4,5,6,7]
c=np.array(b)
print(c)

[1 2 3 4 5 6 7]


zero array

In [47]:
d=np.zeros(2)
print(d)

e=np.zeros(8)
print(e)  #appears as floating

[0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]


In [48]:
f=np.zeros((2,3),dtype=np.int64) #matrix of two rows three columns
print(f)

[[0 0 0]
 [0 0 0]]


ones array

In [49]:
g=np.ones(2)
print(g)

h=np.ones(8)
print(h)  #appears as floating


[1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1.]


Arrange()

In [50]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

linespace() [initial, final, no of digits]

In [51]:
a=np.linspace(2, 10, 5)
b=np.linspace(2, 20, 5)
print(a)
print( b)

[ 2.  4.  6.  8. 10.]
[ 2.   6.5 11.  15.5 20. ]


Eye identity  matrix

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [53]:
a = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.int64)

print(a)

[[1 2 3]
 [4 5 6]]


Indexing and slicing

In [54]:
data = np.array([10, 20, 30, 40, 50, 60])

print("Single element:", data[2])
print("Slice [1:4]:", data[1:4])
print("Last 2 elements:", data[-2:])

# 2D indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nElement at row 1, col 2:", matrix[1, 2])
print("Entire row 0:", matrix[0, :])
print("Entire column 1:", matrix[:, 1])

# Boolean masking : THE most used indexing trick in ML preprocessing
print("\n Boolean masking ")
mask = data > 30
print("Mask:", mask)
print("Filtered values (>30):", data[mask])

# One-liner version, very common in real code
print("Values > 30, one line:", data[data > 30])


Single element: 30
Slice [1:4]: [20 30 40]
Last 2 elements: [50 60]

Element at row 1, col 2: 6
Entire row 0: [1 2 3]
Entire column 1: [2 5 8]

 Boolean masking 
Mask: [False False False  True  True  True]
Filtered values (>30): [40 50 60]
Values > 30, one line: [40 50 60]


Reshaping

In [55]:
arr = np.arange(12)
print("Original:", arr, "shape:", arr.shape)

reshaped = arr.reshape(3, 4)
print("\nReshaped to (3, 4):\n", reshaped)

reshaped_again = arr.reshape(2, 2, 3)
print("\nReshaped to (2, 2, 3):\n", reshaped_again)

flattened = reshaped.flatten()
print("\nFlattened back to 1D:", flattened)


auto_reshape = arr.reshape(4, -1)
print("\nAuto-reshaped (4, -1):\n", auto_reshape)


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11] shape: (12,)

Reshaped to (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2, 2, 3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Flattened back to 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Auto-reshaped (4, -1):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Broadcasting

In [56]:
# Scalar broadcasting
arr = np.array([1, 2, 3])
print("Array + scalar(20):", arr + 20)

# Vector broadcast across a matrix
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
row_vector = np.array([20, 40, 80])

print("\nMatrix:\n", matrix)
print("\nMatrix + row_vector (broadcast across each row):\n", matrix + row_vector)


Array + scalar(20): [21 22 23]

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix + row_vector (broadcast across each row):
 [[21 42 83]
 [24 45 86]
 [27 48 89]]


vectorized math and linear algebra

In [57]:
data = np.array([[1, 2, 3],
                  [4, 5, 6]])

print("Sum of all elements:", data.sum())
print("Sum along columns (axis=0):", data.sum(axis=0))
print("Sum along rows (axis=1):", data.sum(axis=1))
print("Mean:", data.mean())
print("Standard deviation:", data.std())

# Dot product - the core operation in every neural network layer
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\nDot product of two vectors:", np.dot(a, b))

# Matrix multiplication  "inputs times weights"
inputs = np.array([[1, 2], [3, 4]])
weights = np.array([[0.5, 0.1], [0.2, 0.3]])
output = inputs @ weights   # @ is matrix multiplication in NumPy
print("\nInputs:\n", inputs)
print("Weights:\n", weights)
print("Output (inputs @ weights):\n", output)

Sum of all elements: 21
Sum along columns (axis=0): [5 7 9]
Sum along rows (axis=1): [ 6 15]
Mean: 3.5
Standard deviation: 1.707825127659933

Dot product of two vectors: 32

Inputs:
 [[1 2]
 [3 4]]
Weights:
 [[0.5 0.1]
 [0.2 0.3]]
Output (inputs @ weights):
 [[0.9 0.7]
 [2.3 1.5]]
